--create database OKULYONETIMI
--CREATE TABLE BOLUMLER
--(
--ID INT PRIMARY KEY IDENTITY,
--BOLUMADI NVARCHAR(50) NOT NULL
--)
--CREATE TABLE DERSLER
--(
--ID INT PRIMARY KEY IDENTITY,
--DERSADI NVARCHAR(50) NOT NULL,
--DERSKREDI TINYINT NOT NULL,
--BOLUMID INT NOT NULL FOREIGN KEY REFERENCES BOLUMLER(ID)
--)
--CREATE TABLE OGRENCILER 
--(
--ID INT PRIMARY KEY IDENTITY,
--AD NVARCHAR(25) NOT NULL,
--SOYADI NVARCHAR(25) NOT NULL,
--OGRENCINO CHAR(8) NOT NULL,
--EPOSTA VARCHAR(50) NULL,
--BOLUMID INT NOT NULL FOREIGN KEY REFERENCES BOLUMLER(ID)
--)
--CREATE TABLE OGRENCILERINDERSLERI
--(
--ID INT PRIMARY KEY IDENTITY,
--OGRENCIID INT NOT NULL FOREIGN KEY REFERENCES OGRENCILER(ID),
--DERSID INT NOT NULL FOREIGN KEY REFERENCES DERSLER(ID)
--)

--CREATE TABLE SINAVTIPLERI
--(ID INT PRIMARY KEY IDENTITY,
--SINAVTIPI NVARCHAR(50) NOT NULL
--)
--CREATE TABLE OGRENCEIDERSNOTLARI
--(ID INT PRIMARY KEY IDENTITY,
--OGRENCIDERSID INT NOT NULL FOREIGN KEY REFERENCES OGRENCILERINDERSLERI(ID),
--SINAVTIPI INT NOT NULL FOREIGN KEY REFERENCES SINAVTIPLERI(ID),
--ACIKLAMA NVARCHAR(100) NOT NULL,
--NOTU DECIMAL(5,2) NOT NULL
--)

INSERT INTO BOLUMLER(BOLUMADI) values ('Bilgisayar Müh'),('Matematik'),('Fizik')

--INSERT INTO DERSLER(DERSADI,DERSKREDI,BOLUMID) values 

INSERT INTO OGRENCILER(AD,SOYADI,OGRENCINO,BOLUMID)
VALUES 
('ALÝ','VELÝ','123',1),
('AYÞE','FATMA','456',2),
('HASAN','HÜSEYÝN','789',1),
('MUSTAFA','MEHMET','159',3)